//端口  http://repo.dev.smallsaas.cn:8084
//登录 /sys/oauth/login
//精灵市场  /api/crud/oms/wisp/wisps/market
//玩家  /api/crud/oms/player/players
//签到  /api/crud/oms/playerSignRecord/playerSignRecords
//添加预约  /api/crud/oms/wispBookingRecord/wispBookingRecords
//购买能力晶石  /api/crud/oms/companionWispOrder/companionWispOrders/generate





@endpoint = http://repo.dev.smallsaas.cn:8084/api/u/player
###
GET {{endpoint}}
Authorization:Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6OTMsImFjY291bnQiOiJhY2M3NjkxMzQ0NyIsImRvbWFpblVzZXJJZCI6NDIsImlhdCI6MTY0MDU3Njg5OSwianRpIjoiOTMiLCJzdWIiOiJhY2M3NjkxMzQ0NyIsImV4cCI6MTY0MDgzNjA5OX0.r7MDamzIxzmzi630pWg0o8Y0xJTNW20i7IOe5ouoTGTJkJZwZMhSrITRArMJ6DTOW1xBe1J3AC-oQuwOeymQDg
