//端口  http://repo.dev.smallsaas.cn:8084
//登录 /sys/oauth/login
//精灵市场  /api/crud/oms/wisp/wisps/market
//玩家  /api/crud/oms/player/players
//签到  /api/crud/oms/playerSignRecord/playerSignRecords
//添加预约  /api/crud/oms/wispBookingRecord/wispBookingRecords
//购买能力晶石  /api/crud/oms/companionWispOrder/companionWispOrders/generate





@endpoint = http://repo.dev.smallsaas.cn:8086/api/crud/oms/player/profit/orderProfit
###
GET {{endpoint}}
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjoyLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDIwNzEwNDcsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0MjMzMDI0N30.aCNdysXYOPEuH7MyrRgBfTrAV4Kg_p7FeK7PtRz_5LR4Tz3WaNGlGo2XUGmvcbef3soHPcFA3vmCXvaxtv6JJw
