@endpoint = https://api.mock.smallsaas.cn

GET {{endpoint}}/form?id=222333

####
POST {{endpoint}}/form/222333
Content-Type: application/json

{
    "version": "1", 
    "name": "userDetail", 
    "title": "个人资料", 
    "pageStyle": { }, 
    "request": { }, 
    "response": {
        "data": "data"
    }, 
    "container": {

    }, 
    "modules": [
        {
          "type": "autoform", 
          "key": "96afd71a-c8d5-11eb-aca5-0800271e55b7", 
          "name": "基本信息", 
          "container": {
          }
        },
         {
          "type": "autoform", 
          "key": "96afd71a-c8d5-11eb-aca5-0800271e55b6", 
          "name": "账户信息", 
          "navigator":{
              "url":"/defaultPage/page?id=71541",
              "title":"修改账户信息"
          },
          "container": {
          }
        },
         {
          "type": "autoform", 
          "key": "96afd71a-c8d5-11eb-aca5-0800271e55b5", 
          "name": "", 
          "container": {
          }
        },
         {
          "type": "autoform", 
          "key": "96afd71a-c8d5-11eb-aca5-0800271e55b4", 
          "name": "支付密码", 
          "modal":{
              "title":"修改密码",
              "ModalTitle":"修改支付密码",
              "components":[
                {
                    "label": "副手机号验证码",
                    "type": "code",
                    "placeholder": "输入验证码",
                    "requestUrl": ""
                },
                {
                    "label": "新的支付密码",
                    "placeholder": "设置新的支付密码",
                    "field": "paymentPassword",
                    "type":"password"
                }
              ]
          },
          "container": {
          }
        }
    ],
    "moduleData": {
        "96afd71a-c8d5-11eb-aca5-0800271e55b7":{
            "fields": [
                    {
                        "__config__": {
                        "label": "姓名:",
                        "labelWidth": null,
                        "showLabel": true,
                        "tag": "el-input",
                        "tagIcon": "input",
                        "required": false,
                        "layout": "colFormItem",
                        "regList": [],
                        "formId": 113,
                        "renderKey": 1621415432107
                        },
                        "readonly": true,
                        "__vModel__": "name"
                    },
                     {
                        "__config__": {
                        "label": "主手机号码:",
                        "labelWidth": null,
                        "showLabel": true,
                        "tag": "el-input",
                        "tagIcon": "input",
                        "required": false,
                        "layout": "colFormItem",
                        "regList": [],
                        "formId": 113,
                        "renderKey": 1621415432107
                        },
                        "readonly": true,
                        "__vModel__": "mobilePhone"
                    },
                    {
                        "__config__": {
                        "label": "副手机号码:",
                        "labelWidth": null,
                        "showLabel": true,
                        "tag": "el-input",
                        "tagIcon": "input",
                        "required": false,
                        "layout": "colFormItem",
                        "regList": [],
                        "formId": 113,
                        "renderKey": 1621415432107
                        },
                        "canChange":true,
                        "saveAPI":"",
                        "method":"GET",
                        "ModalTitle":"修改副手机号",
                        "components":[
                            {
                                "label":"主手机号验证码",
                                "type":"code",
                                "placeholder":"输入验证码",
                                "requestUrl":""
                            },
                            {
                                "label":"副手机号码",
                                "placeholder":"输入新的副手机号码",
                                "field":"backupMobilePhone"
                            }
                        ],
                        "doNotUseValue":"FROZEN",
                        "statusField":"status",
                        "readonly": true,
                        "__vModel__": "backupMobilePhone"
                    },
                    {
                        "__config__": {
                        "label": "账号状态:",
                        "labelWidth": null,
                        "showLabel": true,
                        "tag": "el-input",
                        "tagIcon": "status",
                        "required": false,
                        "layout": "colFormItem",
                        "regList": [],
                        "formId": 113,
                        "renderKey": 1621415432107
                        },
                        "__slot__":{
                            "options":[
                                {
                                    "label":"已冻结",
                                    "value":"FROZEN",
                                    "color":"#B04849",
                                    "display":true,
                                    "displayLabel":"申请解冻",
                                    "api":"",
                                    "successText":"解冻成功",
                                    "errorText":"解冻失败"
                                },
                                {
                                    "label":"正常",
                                    "value":"NORMAL",
                                    "color":"",
                                    "display":false
                                }
                            ]
                        },
                        "readonly": true,
                        "__vModel__": "status"
                    }
            ],
            "formRef": "elForm",
            "formModel": "formData",
            "size": "medium",
            "labelPosition": "left",
            "labelWidth": 100,
            "formRules": "rules",
            "gutter": 0,
            "disabled": false,
            "formBtns": false,
            "unFocusedComponentBorder": false,
            "loadApi":""
        },
           "96afd71a-c8d5-11eb-aca5-0800271e55b6":{
            "fields": [
                     {
                "__config__": {
                    "layout": "rowFormItem",
                    "tagIcon": "row",
                    "layoutTree": true,
                    "formId": 112,
                    "renderKey": 1621415404383,
                    "componentName": "移动支付账号1",
                    "children": [
                    {
                        "__config__": {
                        "label": "移动账号:",
                        "labelWidth": null,
                        "showLabel": true,
                        "tag": "el-input",
                        "tagIcon": "input",
                        "required": false,
                        "layout": "colFormItem",
                        "regList": [],
                        "formId": 113,
                        "renderKey": 1621415432107
                        },
                        "readonly": true,
                        "__vModel__": "wechatAccount"
                    },
                     {
                        "__config__": {
                        "label": "支付二维码:",
                        "labelWidth": null,
                        "showLabel": true,
                        "tag": "el-image",
                        "tagIcon": "input",
                        "required": false,
                        "layout": "colFormItem",
                        "regList": [],
                        "formId": 113,
                        "renderKey": 1621415432107
                        },
                        "readonly": true,
                        "__vModel__": "wechatQrCodePhotoUrl"
                    }
                    ]
                },
                "type": "default",
                "justify": "start",
                "align": "top"
                }
            ],
            "formRef": "elForm",
            "formModel": "formData",
            "size": "medium",
            "labelPosition": "left",
            "labelWidth": 100,
            "formRules": "rules",
            "gutter": 0,
            "disabled": false,
            "formBtns": false,
            "unFocusedComponentBorder": false,
            "loadApi":""
        },
          "96afd71a-c8d5-11eb-aca5-0800271e55b5":{
            "fields": [
                     {
                "__config__": {
                    "layout": "rowFormItem",
                    "tagIcon": "row",
                    "layoutTree": true,
                    "formId": 112,
                    "renderKey": 1621415404383,
                    "componentName": "银行卡信息",
                    "children": [
                    {
                        "__config__": {
                        "label": "银行卡号:",
                        "labelWidth": null,
                        "showLabel": true,
                        "tag": "el-input",
                        "tagIcon": "input",
                        "required": false,
                        "layout": "colFormItem",
                        "regList": [],
                        "formId": 113,
                        "renderKey": 1621415432107
                        },
                        "readonly": true,
                        "__vModel__": "bankAccountNumber"
                    },
                     {
                        "__config__": {
                        "label": "户名:",
                        "labelWidth": null,
                        "showLabel": true,
                        "tag": "el-input",
                        "tagIcon": "input",
                        "required": false,
                        "layout": "colFormItem",
                        "regList": [],
                        "formId": 113,
                        "renderKey": 1621415432107
                        },
                        "readonly": true,
                        "__vModel__": "bankAccountName"
                    }
                    ]
                },
                "type": "default",
                "justify": "start",
                "align": "top"
                }
            ],
            "formRef": "elForm",
            "formModel": "formData",
            "size": "medium",
            "labelPosition": "left",
            "labelWidth": 100,
            "formRules": "rules",
            "gutter": 0,
            "disabled": false,
            "formBtns": false,
            "unFocusedComponentBorder": false,
            "loadApi":""
        },
            "96afd71a-c8d5-11eb-aca5-0800271e55b4":{
            "fields": [
                    {
                        "__config__": {
                        "label": "支付密码:",
                        "labelWidth": null,
                        "showLabel": true,
                        "tag": "el-input",
                        "tagIcon": "password",
                        "required": false,
                        "layout": "colFormItem",
                        "regList": [],
                         "__slot__": {
                        "prepend": "",
                        "append": ""
                        },
                        "formId": 113,
                        "renderKey": 1621415432107
                        },
                        "tips":"(用于GuGu令)",
                        "readonly": true,
                        "__vModel__": "paymentPassword"
                    }
            ],
            "formRef": "elForm",
            "formModel": "formData",
            "size": "medium",
            "labelPosition": "left",
            "labelWidth": 100,
            "formRules": "rules",
            "gutter": 0,
            "disabled": false,
            "formBtns": false,
            "unFocusedComponentBorder": false,
            "loadApi":""
        }
    }
}