@endpoint = http://repo.dev.smallsaas.cn:8084

### 获取全局配置信息
GET {{endpoint}}/data?id=9999998

### 提交全局配置信息
POST {{endpoint}}/data/9999998
Content-Type: application/json

{
    "formHost":"http://repo.dev.smallsaas.cn:8084/form",
    "dataHost":"http://repo.dev.smallsaas.cn:8084/data",
    "endpoint":"http://repo.dev.smallsaas.cn:8084"
}


    # "formHost":"https://api.mock.smallsaas.cn/form",
    # "dataHost":"https://api.mock.smallsaas.cn/data",
    # "endpoint":"https://api.mock.smallsaas.cn"