@endpoint = http://api.dev.smallsaas.cn:8086

GET {{endpoint}}/form?id=999666
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidXNlclR5cGUiOjEwMSwiYlVzZXJUeXBlIjoiU1lTVEVNIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsImV4dHJhVXNlclR5cGUiOjAsImlhdCI6MTYzOTk5NDE0OSwianRpIjoiMSIsInN1YiI6ImFkbWluIiwiZXhwIjoxNjQwMjUzMzQ5fQ.HY6R-IgAcF8w9jqB9PR8xVQX6QXr0fA--zBlwGKD3vn6lvLJaBYu7dn6wJ7n33rxFVyMJK4EF4TfetioE9kQvg


####
POST {{endpoint}}/form/999666
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidXNlclR5cGUiOjEwMSwiYlVzZXJUeXBlIjoiU1lTVEVNIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsImV4dHJhVXNlclR5cGUiOjAsImlhdCI6MTYzOTk5NDE0OSwianRpIjoiMSIsInN1YiI6ImFkbWluIiwiZXhwIjoxNjQwMjUzMzQ5fQ.HY6R-IgAcF8w9jqB9PR8xVQX6QXr0fA--zBlwGKD3vn6lvLJaBYu7dn6wJ7n33rxFVyMJK4EF4TfetioE9kQvg
Content-Type: application/json

{
    "version": "1", 
    "name": "MyHistory", 
    "title": "我的记录", 
    "pageStyle": { }, 
    "request": { }, 
    "response": {
        "data": "data"
    }, 
    "container": {

    }, 
    "modules": [
        {
            "type":"my-history",
            "key": "95afd71a-c8d5-11eb-aca5-0800271e55b7", 
            "name":"",
            "container":{},
            "binding":{
                "coinsAmount":"coinsAmount",
                "companionWispAmount":"companionWispAmount",
                "recommendPoints":"recommendPoints",
                "tradeUnionPoints":"tradeUnionPoints",
                "marketPoints":"marketPoints",
                "depositPoints":"depositPoints",
                "landRemainingDays":"landRemainingDays",
                "invitingOneBallance":"invitingOneBallance",
                "invitingTwoBallance":"invitingTwoBallance",
                "signBallance":"signBallance",
                "teamBallance":"teamBallance"
            }
        }
    ],
    "dataSource":{
        "api":"/api/u/player/wallet"
    },
    "moduleData": {
    }
}