@endpoint = https://api.mock.smallsaas.cn

### 获取列表页面信息
GET {{endpoint}}/form?id=88888

### 提交列表页面信息
POST {{endpoint}}/form/88888
Content-Type: application/json

{  
    "version": "1",
    "name": "noPayList",
    "title": "未付款列表",
    "pageStyle": {},
    "loadApi": "",
    "response": {
      "data":"data"
    },
    "request": {
    },
    "moduleContainer":{
    },
    "modules": [
      {
        "type": "autolist",
        "name":"",
        "key":"e59992z8-bb88-a788-9922-1623488775885",
        "container":{
            "height":""
        }
      }
    ],
    "moduleData": {
         "e59992z8-bb88-a788-9922-1623488775885": {
            "loadApi":"/api/crud/oms/player/players",
            "itemNavigation": "/index/index?id",
            "response":{
                "list":"list"
            },
            "request":{
                "default":{
                },
                "ps":"pageSize",
                "pn":"pageNo"
            },
            "itemModule":{
                "name":"pay"
            }
        }
    }
}