# @endpoint = https://api.mock.smallsaas.cn
@endpoint = https://api.mock.smallsaas.cn


### 获取列表页面信息
GET {{endpoint}}/form?id=333444

### 提交列表页面信息
POST {{endpoint}}/form/333444
Content-Type: application/json

{  
    "version": "1",
    "name": "MyTeam",
    "title": "我的团队",
    "pageStyle": {
        "margin-top":"20px"
    },
    "loadApi": "",
    "response": {
      "data":"data"
    },
    "request": {
    },
    "moduleContainer":{
    },
    "modules": [
      {
        "type": "autolist",
        "name":"",
        "key":"e59992z8-bb88-a788-9922-1623488775885",
        "container":{
            "height":""
        }
      }
    ],
    "moduleData": {
         "e59992z8-bb88-a788-9922-1623488775885": {
            "loadApi":"/api/u/wisp/market",
            "itemNavigation": "",
            "response":{
                "list":"records"
            },
            "request":{
                "default":{
                },
                "ps":"pageSize",
                "pn":"pageNum"
            },
            "itemModule":{
                "name":"no-pay-new"
            }
        }
    }
}