@endpoint = https://api.mock.smallsaas.cn

GET {{endpoint}}/form?id=444555
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidXNlclR5cGUiOjEwMSwiYlVzZXJUeXBlIjoiU1lTVEVNIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsImV4dHJhVXNlclR5cGUiOjAsImlhdCI6MTYzOTk5NDE0OSwianRpIjoiMSIsInN1YiI6ImFkbWluIiwiZXhwIjoxNjQwMjUzMzQ5fQ.HY6R-IgAcF8w9jqB9PR8xVQX6QXr0fA--zBlwGKD3vn6lvLJaBYu7dn6wJ7n33rxFVyMJK4EF4TfetioE9kQvg


####
POST {{endpoint}}/form/444555
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidXNlclR5cGUiOjEwMSwiYlVzZXJUeXBlIjoiU1lTVEVNIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsImV4dHJhVXNlclR5cGUiOjAsImlhdCI6MTYzOTk5NDE0OSwianRpIjoiMSIsInN1YiI6ImFkbWluIiwiZXhwIjoxNjQwMjUzMzQ5fQ.HY6R-IgAcF8w9jqB9PR8xVQX6QXr0fA--zBlwGKD3vn6lvLJaBYu7dn6wJ7n33rxFVyMJK4EF4TfetioE9kQvg
Content-Type: application/json

{
    "version": "1", 
    "name": "MyTeam", 
    "title": "我的团队", 
    "pageStyle": { }, 
    "request": { }, 
    "response": {
        "data": "data"
    }, 
    "container": {

    }, 
    "modules": [
        {
            "type":"check-team-list",
            "key": "95afd71a-c8d5-11eb-aca5-0800271e55b7", 
            "name":"",
            "container":{},
            "binding":{
            }
        }
    ],
    "dataSource":{
        "api":"/api/u/player/getChildrenById"
    },
    "moduleData": {
    }
}

# @endpoint = https://api.mock.smallsaas.cn


# ### 获取列表页面信息
# GET {{endpoint}}/form?id=444555

# ### 提交列表页面信息
# POST {{endpoint}}/form/444555
# Content-Type: application/json

# {  
#     "version": "1",
#     "name": "Market",
#     "title": "我的团队",
#     "pageStyle": {
#     },
#     "loadApi": "",
#     "response": {
#       "data":"data"
#     },
#     "request": {
#     },
#     "moduleContainer":{
#     },
#     "modules": [
#       {
#         "type": "autolist",
#         "name":"",
#         "key":"e59992z8-bb88-a788-9922-1623488775885",
#         "container":{
#             "height":"",
#             "padding-top":"20px",
#             "background":"#050E17"
#         }
#       }
#     ],
#     "moduleData": {
#          "e59992z8-bb88-a788-9922-1623488775885": {
#             "loadApi":"/api/u/player/getChildrenById",
#             "itemNavigation": "",
#             "response":{
#                 "list":"records"
#             },
#             "request":{
#                 "default":{
#                 },
#                 "ps":"pageSize",
#                 "pn":"pageNum"
#             },
#             "itemModule":{
#                 "name":"spirit-market-new"
#             }
#         }
#     }
# }