# @endpoint = https://api.mock.smallsaas.cn
@endpoint = https://api.mock.smallsaas.cn


### 获取列表页面信息
GET {{endpoint}}/form?id=55555

### 提交列表页面信息
POST {{endpoint}}/form/55555
Content-Type: application/json

{  
    "version": "1",
    "name": "spiritMarket",
    "title": "精灵市场",
    "pageStyle": {
        "background":"red"
    },
    "loadApi": "",
    "response": {
      "data":"data"
    },
    "request": {
    },
    "moduleContainer":{
    },
    "modules": [
      {
        "type": "autolist",
        "name":"",
        "key":"e59992z8-bb88-a788-9922-1623488775885",
        "container":{
            "height":""
        }
      }
    ],
    "moduleData": {
         "e59992z8-bb88-a788-9922-1623488775885": {
            "loadApi":"/api/u/wisp/market",
            "itemNavigation": "/index/index?id",
            "response":{
                "list":"records"
            },
            "request":{
                "default":{
                },
                "ps":"pageSize",
                "pn":"pageNo"
            },
            "itemModule":{
                "name":"spiritMarket"
            }
        }
    }
}


### 获取测试用的列表数据
GET {{endpoint}}/data?id=55555

### 提交测试用的列表数据
POST {{endpoint}}/data/55555
Content-Type: application/json

{
    "list":[
        {}
    ]
}
