@endpoint = http://www.metagugu.net
# 开发环境使用
@devEndpoint = http://localhost:8080

###
GET {{endpoint}}/data?id=1000000

### 主页配置项
### 动态渲染 动态页面
### 说明：
### navs配置底部导航栏样式
### defaultClick 配置默认点击项 0开始
### 配置动态页面渲染的api
POST {{endpoint}}/data/1000000
Content-Type: application/json

{
    "navs":[
        {"title":"精灵广场","image":"/static/public/elvesSquare.png"},
        {"title":"我的精灵","image":"/static/public/MySpirit.png", "showDot": true },
        {"title":"服务中心","image":"/static/public/serviceCenter.png"}
    ],
    "defaultClick":0,
    "api":[
        "?id=41356",
        "?id=41357",
        "?id=666999"
    ]
}