# @endpoint = http://www.metagugu.net
# 开发环境使用
@endpoint = http://49.119.119.7:8082
###
GET {{endpoint}}/data?id=666999
###
POST {{endpoint}}/data/666999
Content-Type: application/json

{
    "tabs":[
        {"title":"團隊","id":"555888"},
        {"title":"未付款列表","id":"333444555"},
        {"title":"直推查询列表","id":"444555"}
    ]
}
